// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9vqThVsaA7H2CmqWgLvGp9NUgrSvOWE',
    appId: '1:750515816652:web:7b27a76b4c8da5be5cda69',
    messagingSenderId: '750515816652',
    projectId: 'beta-testing-cc180',
    authDomain: 'beta-testing-cc180.firebaseapp.com',
    storageBucket: 'beta-testing-cc180.firebasestorage.app',
    measurementId: 'G-RC2FFVT974',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1q3oqflvxRY3czm5pNOQt7CwEHhNTR4g',
    appId: '1:750515816652:android:062a0b5048eee2055cda69',
    messagingSenderId: '750515816652',
    projectId: 'beta-testing-cc180',
    storageBucket: 'beta-testing-cc180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyOfQUVWw5_SXL-idArPJLmYA67yw4CPI',
    appId: '1:750515816652:ios:a25571f29ea05e295cda69',
    messagingSenderId: '750515816652',
    projectId: 'beta-testing-cc180',
    storageBucket: 'beta-testing-cc180.firebasestorage.app',
    iosBundleId: 'com.example.betaTesting',
  );
}
